project_id = "psimanager"

[functions.send-welcome-email]
verify_jwt = false # Webhooks don't send a JWT in the Authorization header

[functions.confirm-scheduling]
verify_jwt = false # Link público para confirmação de agendamento via email/whatsapp
